//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankTransactionViewDto", Namespace="http://schemas.datacontract.org/2004/07/Dto")]
    public partial class BankTransactionViewDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AccountDestinityField;
        
        private string AccountOriginField;
        
        private string BankDestinityField;
        
        private string BankOriginField;
        
        private string ClientDestinityIdentificationField;
        
        private string ClientDestinityNameField;
        
        private string ClientOriginIdentificationField;
        
        private string ClientOriginNameField;
        
        private System.DateTime DateField;
        
        private System.Guid IdTransactionField;
        
        private decimal ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountDestinity
        {
            get
            {
                return this.AccountDestinityField;
            }
            set
            {
                this.AccountDestinityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountOrigin
        {
            get
            {
                return this.AccountOriginField;
            }
            set
            {
                this.AccountOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankDestinity
        {
            get
            {
                return this.BankDestinityField;
            }
            set
            {
                this.BankDestinityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankOrigin
        {
            get
            {
                return this.BankOriginField;
            }
            set
            {
                this.BankOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientDestinityIdentification
        {
            get
            {
                return this.ClientDestinityIdentificationField;
            }
            set
            {
                this.ClientDestinityIdentificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientDestinityName
        {
            get
            {
                return this.ClientDestinityNameField;
            }
            set
            {
                this.ClientDestinityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientOriginIdentification
        {
            get
            {
                return this.ClientOriginIdentificationField;
            }
            set
            {
                this.ClientOriginIdentificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientOriginName
        {
            get
            {
                return this.ClientOriginNameField;
            }
            set
            {
                this.ClientOriginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTransaction
        {
            get
            {
                return this.IdTransactionField;
            }
            set
            {
                this.IdTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankTransactionCreateDto", Namespace="http://schemas.datacontract.org/2004/07/Dto")]
    public partial class BankTransactionCreateDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AccountDestinityIdField;
        
        private System.Guid AccountOriginIdField;
        
        private decimal ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountDestinityId
        {
            get
            {
                return this.AccountDestinityIdField;
            }
            set
            {
                this.AccountDestinityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountOriginId
        {
            get
            {
                return this.AccountOriginIdField;
            }
            set
            {
                this.AccountOriginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOperationOfguid", Namespace="http://schemas.datacontract.org/2004/07/Dto")]
    public partial class ResultOperationOfguid : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountClientDto", Namespace="http://schemas.datacontract.org/2004/07/Dto")]
    public partial class AccountClientDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AccountIdField;
        
        private string AccountNroField;
        
        private string BankField;
        
        private string IdentificationField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                this.AccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNro
        {
            get
            {
                return this.AccountNroField;
            }
            set
            {
                this.AccountNroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank
        {
            get
            {
                return this.BankField;
            }
            set
            {
                this.BankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identification
        {
            get
            {
                return this.IdentificationField;
            }
            set
            {
                this.IdentificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBankTransactionService")]
public interface IBankTransactionService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankTransactionService/GetTransactions", ReplyAction="http://tempuri.org/IBankTransactionService/GetTransactionsResponse")]
    Dto.BankTransactionViewDto[] GetTransactions();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankTransactionService/GetTransactions", ReplyAction="http://tempuri.org/IBankTransactionService/GetTransactionsResponse")]
    System.Threading.Tasks.Task<Dto.BankTransactionViewDto[]> GetTransactionsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankTransactionService/CreateTransaction", ReplyAction="http://tempuri.org/IBankTransactionService/CreateTransactionResponse")]
    Dto.ResultOperationOfguid CreateTransaction(Dto.BankTransactionCreateDto model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankTransactionService/CreateTransaction", ReplyAction="http://tempuri.org/IBankTransactionService/CreateTransactionResponse")]
    System.Threading.Tasks.Task<Dto.ResultOperationOfguid> CreateTransactionAsync(Dto.BankTransactionCreateDto model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankTransactionService/GetAccountClients", ReplyAction="http://tempuri.org/IBankTransactionService/GetAccountClientsResponse")]
    Dto.AccountClientDto[] GetAccountClients();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankTransactionService/GetAccountClients", ReplyAction="http://tempuri.org/IBankTransactionService/GetAccountClientsResponse")]
    System.Threading.Tasks.Task<Dto.AccountClientDto[]> GetAccountClientsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBankTransactionServiceChannel : IBankTransactionService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BankTransactionServiceClient : System.ServiceModel.ClientBase<IBankTransactionService>, IBankTransactionService
{
    
    public BankTransactionServiceClient()
    {
    }
    
    public BankTransactionServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BankTransactionServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BankTransactionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BankTransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Dto.BankTransactionViewDto[] GetTransactions()
    {
        return base.Channel.GetTransactions();
    }
    
    public System.Threading.Tasks.Task<Dto.BankTransactionViewDto[]> GetTransactionsAsync()
    {
        return base.Channel.GetTransactionsAsync();
    }
    
    public Dto.ResultOperationOfguid CreateTransaction(Dto.BankTransactionCreateDto model)
    {
        return base.Channel.CreateTransaction(model);
    }
    
    public System.Threading.Tasks.Task<Dto.ResultOperationOfguid> CreateTransactionAsync(Dto.BankTransactionCreateDto model)
    {
        return base.Channel.CreateTransactionAsync(model);
    }
    
    public Dto.AccountClientDto[] GetAccountClients()
    {
        return base.Channel.GetAccountClients();
    }
    
    public System.Threading.Tasks.Task<Dto.AccountClientDto[]> GetAccountClientsAsync()
    {
        return base.Channel.GetAccountClientsAsync();
    }
}
